# JPA? ???? ?? properties ??
# yaml? xml?? json ?? ???? ?? ??? ???? ??? ?????? ?? ??.
# xml?? json?? ??? ???. ???????? yaml? ???? ??.

debug: false # ??? ??? ?? ??? ??? ? ? ? ?? ??? ??(??true. false: ??-????)
management.endpoints.web.exposure.include: "*" # actuator? endpoint? ????? ??? ? ???? ?. (??? ??? ? ???? ??? ? ? ? ??.)

logging:
  level:
    com.com.bitstudy.app: debug #??????? ???? ?? ??? debug ??? ???? ?
    org.springframework.web.servlet: debug # ? ?? debug? ??. ?? false? ?? request, response ??? ?? ?? ???? ?
    org.hibernate.type.descriptor.sql.BasicBinder: trace #JPA ??? ??? ? ?? ??? ?????? ??? ? ??? ? ? ?? ???? ?????? ? ???? ??. ? ?? ? ? ?? ??? ?.

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: bitstudy
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # ???? DB ???? ??? ? ?? ??. ??? resources ?? data.sql(??? ??? ?) ?? ???? DB? ?? ???? ?????? ?? ? ??.
    hibernate.ddl-auto: create # ???? ?? ??? ???? ???? ???? DDL ???? ??? ?. domain > Article ???? ?? create table ??? ???? ??? ?????? ???? article? articlecComment ???? ??(???? ??? ?? ??? ?)
    show-sql: true # ??????? sql ?? ???? ??
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100


  h2.console.enabled: false #h2 ?? ??? ??
  sql.init.mode: always # data.sql ? ?? ???? ??? ???? ??
  #never(??????), always(?? ???? ???????), embedded(?????)
